# Generated by Django 2.2.3 on 2019-10-21 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paradign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='language',
            name='paradign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Paradign'),
        ),
        migrations.CreateModel(
            name='Programer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ManyToManyField(to='languages.Language')),
            ],
        ),
    ]
